spring:
  application:
    name: desafio
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          lob:
            non-contextual-creation: true
springdoc:
  api-docs:
    path: /swagger-ui.html
  swagger-ui:
    use-root-path: true
    enabled: true
  show-actuator: true
